### ISSUE TITLE
Encounter Tests unable to find Encounter references

### ISSUE THREAD

**Issue by kathypickering** [onc-healthit/inferno-program#153] opened 2020-07-27 22:49 UTC
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
The Encounter Tests are skipped because they are unable to find Encounter references in prior searches.

**Your environment**
* Edition of inferno (Community or Program): https://inferno.healthit.gov/inferno
* Version of inferno: 1.0.2
* Which browser and version(s) is the bug present on?: Chrome Version 83.0.4103.97

**Steps to reproduce**

1. Select a patient 
2. Ensure the patient has references to Encounters on other resources such as AllergyIntolerance or Procedure

Include:

* The selected test suite: Single Patient API Procedure resource
* The URL of the FHIR server being tested\: https://fhir-open.sandboxcerner.com/r4/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca
* The Test ID, if it's a problem with a specific test:  USCE-1 through 4
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
We would expect any Encounter reference from any other Test would qualify and be able to be tested in the Encounter Tests.

**Actual behavior**
All Encounter Tests are skipped.

https://inferno.healthit.gov/inferno/coutjwtxOCO/

**Comment by arscan** [comment] 2020-07-27 22:56
Thanks for the report!  I took a look and there are definitely Encounter references, for example in MedicationRequest:

<img width="870" alt="Screen Shot 2020-07-27 at 6 55 24 PM" src="https://user-images.githubusercontent.com/412901/88599856-cdf09c80-d03a-11ea-8aaf-9c8790e4bc31.png">

We'll have to figure out why that isn't being picked up in the later tests.

**Comment by arscan** [comment] 2020-07-28 01:08
I believe I found the issue, and think our tests are functioning as intended.

The Encounter test is only concerned with references to Encounter resources that it knows MUST support the US Core Encounter profile.  And it turns out that not all references to Encounter resources within other US Core profiles need to conform to the US Core Encounter profile:

> Many of the profiles in this guide reference other FHIR resources that are also US Core profiles. This is defined in the formal profile definitions. For example, US Core CareTeam Profile references US Core Patient. For any other references not formally defined in a US Core profiles, the referenced resource SHOULD be a US Core profile if a US Core profile exists for the resource type. For example, although Condition.asserter is not constrained by this guide, the reference to Patient or Practitioner SHOULD be a valid US Core Patient or US Core Practitioner.

https://www.hl7.org/fhir/us/core/general-guidance.html#referencing-us-core-profiles

Now that I look at the above `MedicationRequest` example I found earlier, I realize that [MedicationRequest.encounter](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-medicationrequest-definitions.html#MedicationRequest.encounter) element is of type `Reference(Encounter)`, not `Reference(US Core Encounter)`, and we cannot expect for certainty that the resource that resolves at that reference conforms to the US Core Encounter profile.  Therefore, we do not save that specific reference for use later.

I see that you also have an Encounter reference on [AllergyIntolerance.encounter](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-allergyintolerance-definitions.html#AllergyIntolerance.encounter) and [Procedure.encounter](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-procedure-definitions.html#Procedure.encounter), but those are of type `Reference(Encounter)` too.

For an example of a reference to `Reference(US Core Encounter)`, see US Core Diagnostic Report Note's [encounter](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-diagnosticreport-note-definitions.html#DiagnosticReport.encounter) element.  [DocumentReference.context.encounter](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-documentreference-definitions.html#DocumentReference.context.encounter) is another example.

If you place encounter references in one of those spots, you should start getting references that are tested in the Encounter test.

**Comment by arscan** [comment] 2020-08-07 20:48
I'm going to close this ticket because I believe I answered your question. Please feel free to follow up with another ticket if you still have questions.

**Closed by arscan** 2020-08-07 20:48 UTC
