### ISSUE TITLE
Internal Service Error: Standalone Patient App - Full Patient Access

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#438] opened 2022-02-22 15:32 UTC
**Subject of the issue**
This will likely be a tough one to debug: The "Standalone Patient App: Full Patient Access" tests fail on test 7 (AVU-07 Device scope) of "Unrestricted Resource Type Access":

![image](https://user-images.githubusercontent.com/20422272/155159592-7cdabd91-ad3a-4e46-bedb-999ce7eca5f6.png)

Click Cancel Sequence:
URL:  https://inferno.healthit.gov/inferno/9vYnVU91mZW/test_sets/test_procedure/sequence_result/ef6f8bf5-c7e6-42ae-bf3e-24f9aac1520d/cancel
![image](https://user-images.githubusercontent.com/20422272/155160006-363dc2c1-7cc1-44f0-bce3-5dc2f2989725.png)

![image](https://user-images.githubusercontent.com/20422272/155164270-5663ec8f-9275-4c90-a2e0-47bc2f4b5c2f.png)

**Your environment**
* Edition of inferno (Community or Program): ONC
* Version of inferno:  1.9.0
* Which browser and version(s) is the bug present on?: Chrome Version 96.0.4664.110 (Official Build) (x86_64)

**Steps to reproduce**

1. Inferno>ONC Edition>input endpoint
2. Standalone Patient App Tab> Run Tests> input client ID and secret>update Practitioner, Organization and Location scopes to 'user' (instead of patient)>execute
3. Launch Portal login/authorization window by clicking continue in the pop up
4. Sign in with patient credentials
5. Authorize access
6. Tests run but fail on the Device scope test AVU-07 and throws an Internal service error - no tests results are provided -hard stop failure

Include:

* The selected test suite
* The URL of the FHIR server being tested:  https://fhir-myrecord.cerner.com/r4/17316440-14fe-4957-b62f-9d85de2c88ca
* The Test ID, if it's a problem with a specific test: AVU-07
* Any required configuration options (client ID, client secret, etc.)

- This is our prod environment so trying to avoid sharing this data publicly if we can avoid it. I would be happy to demo this on a  call if appropriate or try to send info via an encrypted email. Let me know!

* Anything else needed to make the issue occur.

**Expected behavior**
This was working perfectly the other day. However, in our testing we needed to add some freetext Device data in order to show how we handle unknown DARs for the Single Patient tests later. Now the access tests are failing. So we assume this is related to the freetext data we entered but feel like it should not be failing.

Not only does the progress bar stop on test 7 (AVU-07 Device scope) but I can also bypass this issue if I deselect "Device" in my  patient authorization screen. Then all tests run and provide proper results.

**Actual behavior**
Hard failure. No tests provide results. It's  almost as though the whole thing times out.

**Comment by yunwwang** [comment] 2022-02-25 16:47
This is similar to #439

**Comment by bh021790** [comment] 2022-02-25 16:55
I thought it might be! Ashoka is my bud and he is investigating his issue further! Thanks for the response!

**Comment by arscan** [comment] 2022-04-26 16:23
I'm going  to close this as a duplicate of #439 for now.  Let us know if you do not think this is the case.

Thanks!

**Closed by arscan** 2022-04-26 16:23 UTC
