### ISSUE TITLE
Inferno Test USCPO-10 is failing for Observation Pulse Oximetry codings

### ISSUE THREAD

**Issue by cmilligan11** [onc-healthit/inferno-program#350] opened 2021-08-23 17:50 UTC
Inferno Single Patient API Pulse Oximetry test USCPO-10 is failing with the following errors:
* Observation/127864: Observation.code.coding failed cardinality test (1..1) – found 2
* Observation/127864: Observation.code.coding.code value of '59408-5' did not match fixed value: 2708-6
* Observation/127864: Observation.code.coding failed cardinality test (1..1) – found 2
* Observation/127864: Observation.code.coding.code value of '2708-6' did not match fixed value: 59408-5
* Observation/127864: Observation.component.code CodeableConcept did not match defined pattern: {"coding"=>[ {"system"=>"http://loinc.org", "code"=>"3150-0"}
]}

**Environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: Inferno Program Edition v1.6.2
* Which browser and version(s) is the bug present on?: Chrome and Safari (only two browsers tested with)

**Observation Response**
```
{
  "effectiveDateTime": "2021-08-23",
  "resourceType": "Observation",
  "subject": {
    "reference": "Patient/123",
    "type": "Patient"
  },
  "status": "final",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/us/core/StructureDefinition/us-core-pulse-oximetry"
    ]
  },
  "valueQuantity": {
    "unit": "percent",
    "system": "http://unitsofmeasure.org",
    "value": 98,
    "code": "%"
  },
  "identifier": [
    {
      "system": "https://fhir.athena.io/sid/ah-observation",
      "value": "127864"
    }
  ],
  "component": [
    {
      "code": {
        "coding": [
          {
            "system": "http://loinc.org",
            "code": "3151-8",
            "display": "Inhaled oxygen flow rate"
          }
        ]
      },
      "valueQuantity": {
        "unit": "liter per minute",
        "system": "http://unitsofmeasure.org",
        "value": 3,
        "code": "L/min"
      }
    }
  ],
  "id": "127864",
  "category": [
    {
      "text": "Clinical observations measure the body's basic functions such as blood pressure, heart rate, respiratory rate, height, weight, body mass index, head circumference, pulse oximetry, temperature, and body surface area.",
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/observation-category",
          "code": "vital-signs",
          "display": "Vital Signs"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "http://loinc.org",
        "code": "2708-6",
        "display": "Oxygen saturation in Arterial blood"
      },
      {
        "system": "http://loinc.org",
        "code": "59408-5",
        "display": "Oxygen saturation in Arterial blood by Pulse oximetry"
      }
    ]
  }
}
```

It seems that the correct codes are included for the PulseOx and SatO2 coding slices according to http://hl7.org/fhir/us/core/StructureDefinition-us-core-pulse-oximetry-definitions.html#Observation.code.coding 
We have tried swapping the ordering of the codes, but still get the same error.

**Comment by yunwwang** [comment] 2021-08-23 18:17
@cmilligan11 Did you run this on inferno.healthit.gov?

I imported the resource provided on my devbox. The resource passed USCPO-10 test.

![image](https://user-images.githubusercontent.com/8761175/130496614-95586887-681e-4479-aa11-8ef5985a2cf4.png)

**Comment by cmilligan11** [comment] 2021-08-23 18:43
We're running private versions of Inferno for testing, which is based on https://github.com/onc-healthit/inferno

**Comment by yunwwang** [comment] 2021-08-23 18:51
Oh, that is community edition. The problem edition is dedicated for ONC certification test.

**Comment by cmilligan11** [comment] 2021-08-23 19:02
I think I just linked the wrong version. We have both a Community and Program edition. The tests that I've run have been on the Program Edition

**Comment by yunwwang** [comment] 2021-08-23 21:25
@cmilligan11: I reproduced your problem by changing the `resource valiator` in config.yml to `internal`. Please verify if that is the setting you use locally. The internal validator has limited functionality on validating FHIR base resources. The recommended setting is using external validator service.

Please follow the instruction [here](https://github.com/onc-healthit/inferno-program#validator-service) to get validator service installed or upgraded.

Please let me know if you still experience the same problem after changing to `external` validator

**Comment by cmilligan11** [comment] 2021-08-23 22:47
I confirmed we have `resource_validator: internal` set.  Thanks! I'll let you know if we still have the same problem after switching.

**Comment by nathanloyer** [comment] 2021-08-24 20:36
We're going to try that out soon, I just wanted to note that we don't use the latest version in the main/master branch here, we're set at the release versions in the docker images. Currently we're on 1.6.2

**Comment by nathanloyer** [comment] 2021-08-24 22:17
@yunwwang it looks like inferno program edition is expecting us to use version 1.2.0 of the validator. We currently have 1.4.0 deployed and I was looking at updating to 2.0.0. Are there known compatibility issues? If not, can that check be updated? Or should we be using 1.2.0..? I believe there were some fixes in 1.4.0 that my team requested.

**Comment by yunwwang** [comment] 2021-08-25 14:33
@nathanloyer 

Inferno Program v1.6.2 is the latest published version. The main branch contains several changes for v1.7.0 which will be released soon.

Inferno validator v1.4.0 uses the FHIR validator v5.3.14. Inferno validator v1.2.0 uses FHIR validator v5.2.10. Though you can run Inferno Program edition with any validator releases after v1.2.0, the results at some edge cases could be different. We recommend to use the same Inferno validator version (v1.2.0) as the certification test environment uses. 

You can install Inferno validator v1.2.0 using its docker image: 

```
docker pull infernocommunity/fhir-validator-service:v1.2.0
docker run -p [your_port]:4567 -e DISABLE_TX=true infernocommunity/fhir-validator-service:v1.2.0
```

Or you can check out the specific commit in master branch with tag `v1.2.0`

**Comment by yunwwang** [comment] 2021-11-01 18:30
@cmilligan11 I will close this ticket as question has been answered. If you are still experience the same problem, please either reopen this issue or create a new one. Thank you.

**Closed by yunwwang** 2021-11-01 18:30 UTC
Labels: wontfix
