### ISSUE TITLE
Observation for Heart Rate, Body Temp, Respiratory Rate requiring Observation.effective[x]: minimum required = 1 but there is an effectiveDateTime in the json

### ISSUE THREAD

**Issue by jhrpcek** [onc-healthit/inferno-program#363] opened 2021-09-21 18:09 UTC
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
Describe your issue here.
 Observation: Observation.effective[x]: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/resprate)  

json contains effectiveDateTime which is a valid field for the effective field 
{
  "subject": {
    "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
    "type": "Patient"
  },
  "meta": {
    "lastUpdated": "2021-09-18T21:39:49.829963Z",
    "versionId": "14"
  },
  "status": "final",
  "effectiveDateTime": "2021-05-20T09:55:00-05:00",
  "method": {
    "text": "APICAL"
  },
  "referenceRange": [
    {
      "low": {
        "unit": "bpm",
        "system": "http://unitsofmeasure.org",
        "code": "/min",
        "value": 50
      },
      "high": {
        "unit": "bpm",
        "system": "http://unitsofmeasure.org",
        "code": "/min",
        "value": 120
      },
      "text": "Critical Range"
    }
  ],

**Your environment**
* Edition of inferno (Community or Program): Program 
* Version of inferno: 1.6.2
* Which browser and version(s) is the bug present on?: Chrome
The version of the HL7 Validator currently used for validation is 1.2.0.

**Steps to reproduce**
Tell us how to reproduce this issue.  
Create a vital sign with an effectiveDateTime value. 

Include:

* The selected test suite:   Single Patient API:    Observation Respiratory Rate Tests, Observation Heart Rate Tests, Observation Body Temperature Tests -   step  USCOHR-10 in each. 
* The URL of the FHIR server being tested
* * The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Tell us what should happen.

Inferno should accept an effectiveDateTime or effectivePeriod field in the json for the effective 

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.

**Comment by yunwwang** [comment] 2021-09-21 22:48
@jhrpcek can you post the whole resource (after removing any sensitive data)?

**Comment by jhrpcek** [comment] 2021-09-21 23:18
yes - here's the heart rate full json: 
{
  "resourceType": "Bundle",
  "id": "7bbc5f60-f778-4114-99f3-cdf5fdad2e84",
  "meta": {
    "lastUpdated": "2021-09-21T21:49:10.240Z"
  },
  "type": "searchset",
  "total": 10,
  "link": [
    {
      "relation": "self",
      "url": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation?code=8867-4&patient=7b0fe2ec-e479-4767-9565-ca2208c0c181"
    }
  ],
  "entry": [
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/723298a3-0156-40f4-84a2-1b94b1d8fdcf",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/b64dc2dd-bc4d-4f74-86f1-266f5caaa2e7",
            "display": "CSIGLER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-03T04:36:00-05:00",
        "interpretation": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
                "code": "LL",
                "display": "Critical Low"
              }
            ]
          }
        ],
        "meta": {
          "lastUpdated": "2021-09-18T21:39:48.509263Z",
          "versionId": "12"
        },
        "id": "723298a3-0156-40f4-84a2-1b94b1d8fdcf",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 45
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/050324a9-bcbf-4ce8-8e8f-28538298cfb1",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/6187cd1a-2f46-4dfb-94d6-ce7914f190bb",
            "display": "EMRUSER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/ab605134-1546-4ad5-a796-b21d8e5ffc01",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-18T09:05:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:49.597882Z",
          "versionId": "5"
        },
        "id": "050324a9-bcbf-4ce8-8e8f-28538298cfb1",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 110
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/1d7e2713-838d-4aa3-85ce-095536333835",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/6187cd1a-2f46-4dfb-94d6-ce7914f190bb",
            "display": "EMRUSER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/ab605134-1546-4ad5-a796-b21d8e5ffc01",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-18T10:33:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:50.107212Z",
          "versionId": "4"
        },
        "id": "1d7e2713-838d-4aa3-85ce-095536333835",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 111
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/a503e5db-7d3e-4b4e-9efa-787923366aa3",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/6187cd1a-2f46-4dfb-94d6-ce7914f190bb",
            "display": "EMRUSER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-13T16:27:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:50.623138Z",
          "versionId": "8"
        },
        "id": "a503e5db-7d3e-4b4e-9efa-787923366aa3",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 110
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/350d70d6-30ec-4ce6-8d54-d0e702f08a2e",
      "resource": {
        "note": [
          {
            "text": "Pulse comments for testing"
          },
          {
            "text": "Testing General Comments"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/b64dc2dd-bc4d-4f74-86f1-266f5caaa2e7",
            "display": "CSIGLER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-03T07:35:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:48.817227Z",
          "versionId": "12"
        },
        "id": "350d70d6-30ec-4ce6-8d54-d0e702f08a2e",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 115
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/d15f90b1-6408-4d92-a298-03a33560d158",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/6187cd1a-2f46-4dfb-94d6-ce7914f190bb",
            "display": "EMRUSER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-05-20T09:55:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:49.829963Z",
          "versionId": "14"
        },
        "id": "d15f90b1-6408-4d92-a298-03a33560d158",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 88
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/ddd9fdf6-4171-4bc4-8740-84b4e9eb3571",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/6187cd1a-2f46-4dfb-94d6-ce7914f190bb",
            "display": "EMRUSER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "meta": {
          "lastUpdated": "2021-09-18T21:39:49.908324Z",
          "versionId": "14"
        },
        "id": "ddd9fdf6-4171-4bc4-8740-84b4e9eb3571",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 85
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/e5af88cc-54c8-4bbb-9bac-0a9e68d82b1f",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/6187cd1a-2f46-4dfb-94d6-ce7914f190bb",
            "display": "EMRUSER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-13T17:42:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:50.890771Z",
          "versionId": "8"
        },
        "id": "e5af88cc-54c8-4bbb-9bac-0a9e68d82b1f",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 110
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/eb75db1a-f1a7-4908-9fe6-c0c9f7b5d30c",
      "resource": {
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/6187cd1a-2f46-4dfb-94d6-ce7914f190bb",
            "display": "EMRUSER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/ab605134-1546-4ad5-a796-b21d8e5ffc01",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-10T13:17:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:50.335213Z",
          "versionId": "10"
        },
        "id": "eb75db1a-f1a7-4908-9fe6-c0c9f7b5d30c",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 110
        }
      }
    },
    {
      "search": {
        "mode": "match"
      },
      "fullUrl": "https://fhir-qa-1.test.yourcareuniverse.net/tenant/7db7dfb5-2f73-4b96-bcf1-131410518850/Observation/30f4190e-1d1b-4761-b1e0-25848a277e0f",
      "resource": {
        "note": [
          {
            "text": "This is a test for general comments for Vital Sign"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "8867-4",
              "display": "Heart rate"
            }
          ],
          "text": "HEART RATE"
        },
        "performer": [
          {
            "reference": "Practitioner/b64dc2dd-bc4d-4f74-86f1-266f5caaa2e7",
            "display": "CSIGLER",
            "type": "Practitioner"
          }
        ],
        "method": {
          "text": "APICAL"
        },
        "subject": {
          "reference": "Patient/7b0fe2ec-e479-4767-9565-ca2208c0c181",
          "type": "Patient"
        },
        "encounter": {
          "reference": "Encounter/76af5161-b06f-4a61-b54c-16aa9c62285e",
          "type": "Encounter"
        },
        "referenceRange": [
          {
            "high": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 120
            },
            "low": {
              "unit": "bpm",
              "system": "http://unitsofmeasure.org",
              "code": "/min",
              "value": 50
            },
            "text": "Critical Range"
          }
        ],
        "effectiveDateTime": "2021-09-03T07:42:00-05:00",
        "meta": {
          "lastUpdated": "2021-09-18T21:39:49.248268Z",
          "versionId": "12"
        },
        "id": "30f4190e-1d1b-4761-b1e0-25848a277e0f",
        "category": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                "code": "vital-signs",
                "display": "Vital Signs"
              }
            ],
            "text": "Vital Signs"
          }
        ],
        "resourceType": "Observation",
        "status": "final",
        "valueQuantity": {
          "unit": "bpm",
          "system": "http://unitsofmeasure.org",
          "code": "/min",
          "value": 110
        }
      }
    }
  ]
}

**Comment by yunwwang** [comment] 2021-09-22 13:57
@jhrpcek I could not reproduce the error with those Observation resources provided. If you are using inferno.healthit.gov, do you have a test id so I can check saved tests results?

**Comment by jhrpcek** [comment] 2021-09-22 14:47
I ran the test on our internally installed program version of 1.6.2 that has the version of the HL7 Validator set to 1.2.0.
Is that the same that you were trying?

**Comment by yunwwang** [comment] 2021-09-22 19:27
Hmm. Yes. That is the same as I have. Do you use docker image or ruby source codes?

**Comment by jhrpcek** [comment] 2021-09-23 13:03
docker image

**Comment by yunwwang** [comment] 2021-09-23 16:39
@jhrpcek This is really strange. Would you mind to do more testing to see
1) if this is random
2) could you take a screenshot of the failed test result. (on the failed test, click "results" link)
3) if possible, could you run test on inferno.healthit.gov?

**Comment by jhrpcek** [comment] 2021-09-23 18:33
1.  I tried on a different patientId - i don't get that specific error but I am getting other similar errors in our internal environment that I don't get when running same patientId on the inferno.healthit.gov site.    For the DiagnosticReport For Report And Note Exchange Tests i'm getting:  USCDRRN-12: All must support elements are provided in the DiagnosticReport resources returned. results...2. Could not find presentedForm in the 4 provided DiagnosticReport resource(s).   But I don't get that running on on inferno.healthit.gov  even though the json only has a data-absent-reason extension in that field. 

2. I can take a screensheet, yes.    
![image](https://user-images.githubusercontent.com/91143247/134563886-91020641-c96e-4405-9bdb-a7fbbe45315a.png)

![image](https://user-images.githubusercontent.com/91143247/134563975-38b94706-4446-44de-8de4-3968a8f42306.png)

3. I was able to run on inferno.healthit.gov and I believe it's not doing the validations correctly.  I saved my test run: https://inferno.healthit.gov/inferno/1VTedrpxQ9k/    and it's not flagging the presentedForm as an error even though you said data-absent-reason extension isn't supposed to be used to pass this test.
4. I also saved my test run from our locally installed same version:  can you get to this?   https://inferno.mhdidevxasayd.com/inferno/8KknWMQRtmU/

**Comment by jhrpcek** [comment] 2021-09-23 18:40
Another example is on Patient Tests: 
1) internal inferno says this skipped test - but there are no errors in this run https://inferno.healthit.gov/inferno/1VTedrpxQ9k/ 
even though you can see the race is clearly missing in that run. 

 USCP-13: All must support elements are provided in the Patient resources returned. results...
Could not find address.period, Patient.extension:race in the 1 provided Patient resource(s)
![image](https://user-images.githubusercontent.com/91143247/134564818-093da233-111d-419f-a88e-f1d46a9a5b0b.png)

**Comment by yunwwang** [comment] 2021-09-23 19:00
@jhrpcek Those MustSupport issues are similar to what I have explain in the other one. I am more curious about the failed HeartRate due to missing effectiveTime. Could you take a screenshot for the failed test result of USCOHR-10?

**Comment by jhrpcek** [comment] 2021-09-23 21:09
I can, but I guess my point was there seems to be a difference between the docker image we installed(we just re-installed it to be sure) and the healthit one...
Here's the screenshot from ours: 
![image](https://user-images.githubusercontent.com/91143247/134584449-87e1b582-0bb0-4532-ac20-d1189e227e6c.png)

**Comment by yunwwang** [comment] 2021-09-23 21:35
First, I would like to confirm that the "minimum require = 1" error is correctly reported. So we can put it aside.

**Comment by yunwwang** [comment] 2021-09-23 21:42
Second, for the difference on the MustSupport test, are you sure you used the same patient when testing locally and online. One small difference I noticed is that the online report indicate there are three DiagnosticReport resources tested while your local results indicated four DiagnosticReport resources tested.

**Comment by jhrpcek** [comment] 2021-09-23 21:43
Yes- i can confirm that the specific observationId's listed do not contain effectiveDateTime.  So we are good there.

**Comment by jhrpcek** [comment] 2021-09-23 23:52
Yes, i was using the same patient for both.  There's 3 diagnostic reports shown in both runs. I'm not sure why skipped message says there's 4 provided, but i only find 3 and they are the same in both locally and online.    It doesn't list out the 4 id's in that test. 
 PATHOLOGY "id": "abf17316-61e2-415c-8519-8cb687ac34a2"
 cat scan    "id": "3f16d2c8-384e-4b16-b9a9-41c2314d646f"
  cardiology       "id": "02003082-1af4-4f29-94b0-a91b1859b1ac",

![image](https://user-images.githubusercontent.com/91143247/134598353-d5ce1f06-b0c2-43ac-87fa-767217c8c30e.png)

**Comment by jhrpcek** [comment] 2021-09-24 14:45
Re-ran online and no errors for this patient for DiagnosticReport For Report And Note Exchange Tests. 
Re-ran locally and now I am only getting the 3 diagnosticReport id's returned in the other steps, but the error message for step 12 is still saying there are 4, is it possible to update Inferno to show the requests for step 12?

![image](https://user-images.githubusercontent.com/91143247/134691948-ad6cd893-b0e4-4d67-8b29-3adbafb8413f.png)

Here's the screenshot from step 11 where it shows only 3 returned from step 1: 
![image](https://user-images.githubusercontent.com/91143247/134692152-e698e1a8-4466-40ad-8cb7-5b76d056276e.png)

**Comment by yunwwang** [comment] 2021-09-24 15:52
Oh, I see. You used DAR extension for presentedForm. As mentioned in another issue, DAR should not counted as a way to pass MustSupport. We are release v1.7.0 now. So please test again with v1.7.0 to check if the same behavior exists.

**Comment by yunwwang** [comment] 2021-09-24 16:15
@jhrpcek I will close this ticket since the original question is already answered and we have another issue about MustSupport.

**Closed by yunwwang** 2021-09-24 16:15 UTC
Labels: wontfix
