### ISSUE TITLE
When source system does not have data for Must Support data element

### ISSUE THREAD

**Issue by kathypickering** [onc-healthit/inferno-program#143] opened 2020-07-20 16:51 UTC
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
When the source system does not have data for a Must Support data element such as Procedure.performed[x], a data absent reason is not passing the scenario per the general guidance.
https://www.hl7.org/fhir/us/core/general-guidance.html#must-support

**Your environment**
* Edition of inferno (Community or Program): https://inferno.healthit.gov/inferno
* Version of inferno: 1.0.2
* Which browser and version(s) is the bug present on?:  Chrome Version 83.0.4103.97

**Steps to reproduce**
Patient with a procedure that is missing performed[x] that is populated with a data-absent-reason extension

Include:

* The selected test suite: Single Patient API Procedure resource
* The URL of the FHIR server being tested https://fhir-open.sandboxcerner.com/r4/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca
* The Test ID, if it's a problem with a specific test. USCPROC-09
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
Returning Procedure.performed[x] with data-absent-reason extension should pass
  "_performedDateTime": {
    "extension": [
      {
        "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason",
        "valueCode": "unknown"
      }
    ]
  },

Is there something wrong with how the data-absent-reason is populated?

**Actual behavior**
Tell us what happens instead. Include screenshots if possible.
Returning Procedures.performed[x] with data-absent-reason extension is failing USCPROC-09
![image](https://user-images.githubusercontent.com/39627539/87963765-dbc48180-ca7e-11ea-8921-bd0ea296cf5d.png)

**Comment by yunwwang** [comment] 2020-07-20 19:09
Hello kathypickering:
Thank you for reaching to Inferno test.
After brief investigation, we noticed that Procedure.performed[x] is mandatory by US Core Procedure profile which mean the resource must have this element populated.

**Comment by kathypickering** [comment] 2020-07-20 20:47
Procedure.performed[x] is NOT base spec required; it is US Core Must Support.  Per general guidance regarding missing data, we are allowed to populate with the data-absent-reason extension and should not fail. 
https://www.hl7.org/fhir/us/core/general-guidance.html#missing-data

**Comment by yunwwang** [comment] 2020-07-20 21:36
According to US Core Procedure profile https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-procedure.html
The cardinality of performed[x] is 1..1 which mean this element is mandatory.
![image](https://user-images.githubusercontent.com/8761175/87989137-1a6e3200-caa7-11ea-91e2-0648686d5c74.png)

**Comment by yunwwang** [comment] 2020-07-20 22:15
Hello kathypickering: Can you send me an example of Procedure resource which failed the test or the test ID for the save testing session. I would like to take a closer look. Thank you.

**Comment by kathypickering** [comment] 2020-07-20 22:57
https://inferno.healthit.gov/inferno/ksjGrcozm0Y/
https://fhir-open.sandboxcerner.com/r4/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca/Procedure/46806555

**Comment by kathypickering** [comment] 2020-07-21 19:15
Hello yunwwang:  do you need any more information?

**Comment by yunwwang** [comment] 2020-07-21 23:00
These are good. We are investigating the issue. Thank you.

**Comment by kathypickering** [comment] 2020-07-24 18:04
Will your patches correct any US Core Must Support field that is populated with the data-absent-reason extension or do each have to be reported when found?

**Comment by arscan** [comment] 2020-07-24 21:25
This should fix a whole class of errors where primitive extensions are necessary in order for a resource to validate. The most common time this would happen is for mandatory (cardinality >= 1) elements that are filled in with a Data Absent Reason extension instead of a value.  I believe this is the case for Procedure.performed[x], because while the base fhir spec says it has a cardinality of 0..1, US Core set it to 1..1.   Regardless though, you should be able to fill in a data absent reason here instead of a value to meet the 1..1 requirement, and this fix makes sure you can.

Once we merge this fix in and release it you can try it out and let us know if you are still seeing issues.  You shouldn't have to open a report for each individually if it looks like they have the same root cause.

Thanks for the report.  This was a big oversight on our part.  We'll let you know when this is in!

**Comment by arscan** [comment] 2020-07-28 20:21
This autoclosed due to merging a PR -- reopening so we can close when we confirm the fix is in a release.

**Comment by arscan** [comment] 2020-07-31 14:40
We resolved this in [v1.1](https://github.com/onc-healthit/inferno-program/releases/tag/v1.1.0P), which was released and deployed yesterday.   We confirmed it fixes the situation when performedDateTime uses the DAR extension specifically, but it should resolve this whole class of failures where DARs are being used on mandatory (cardinality > 0) elements.

Thanks for the report!

**Closed by arscan** 2020-07-31 14:40 UTC
