### ISSUE TITLE
Question: Will USCCT-08 be removed or noted as Omitted if unable to test? (FI-1350)

### ISSUE THREAD

**Issue by bh021790** [onc-healthit/inferno-program#284] opened 2021-05-10 18:36 UTC
Per this decision (https://jira.hl7.org/browse/FHIR-29768) I'm curious if the CareTeam test will be removed from Inferno or noted as "Omitted", rather than skipped, like I have seen in other sections?

**Comment by bh021790** [comment] 2021-06-11 17:33
Somewhat related question (happy to create a new post/issue if needed). MedicationRequest expects a compositeOr search which I believe we support but the test is being skipped. Am I misunderstanding what the test is looking for?

![image](https://user-images.githubusercontent.com/20422272/121727040-ffd2ec00-cab0-11eb-9a43-899785b3f285.png)

![image](https://user-images.githubusercontent.com/20422272/121727093-0eb99e80-cab1-11eb-9486-412ad1eab0c0.png)

Both calls are successful in postman so just curious why the test would be skipped. Thanks for your help!

ONC Program Edition
Endpoint: https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d
Google Chrome
Inferno 1.6.0

**Comment by yunwwang** [comment] 2021-07-13 17:44
Hello @bh021790 

I double checked the first query https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/MedicationRequest?patient=12744438
All the five results have the same intent=order.

That is why the USCMR-13 skipped because it could not find the 2nd intent value to run the multiple OR test

If you do have another patient that having more than one intent values, you should use that patient to run the test again.

If the server supports only intent=order, then it is the same as original issue.

**Comment by bh021790** [comment] 2021-07-19 14:24
@yunwwang - my apologies. Here is a better example:
https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/MedicationRequest?patient=12753537

- id=330623635 has an intent of 'plan'
- id=330623651 has an intent of 'order'

https://fhir-open.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d/MedicationRequest?patient=12753537&intent=order,plan 

The above request works just fine in Postman but the Inferno test is still skipped:

![image](https://user-images.githubusercontent.com/20422272/126175180-25216977-3058-4b19-a714-b3ffdd7128b7.png)

and the first test works with different intents:

![image](https://user-images.githubusercontent.com/20422272/126175821-e87a320b-42d4-4c77-b721-7bb6982746b7.png)

I recall from last week's Inferno Monthly Sync Up that this test may be changing?

**Comment by yunwwang** [comment] 2021-07-22 20:26
The failure is not related to the `intent`. This test is for the requirement

SHALL support searching using the combination of the patient and intent and status search parameters:

    including support for composite OR search on intent (e.g.intent={system|}[code],{system|}[code],...)
    including support for composite OR search on status (e.g.status={system|}[code],{system|}[code],...)

So the test has two steps, first test composite-OR on status value. Then test composite-OR on intent value. The test skipped on the first test, composite OR search on status.

**Comment by cooperthompson** [comment] 2021-07-30 22:00
> However, you could argue that our tests have created a requirement that shouldn't exist by needing to see two distinct statuses to prove support for multipleOr searches. Perhaps you can correctly claim to support multipleOr at the API level, but simply will never have enough data to show two different matching values. So you could accept a search like `CareTeam?patient=5&status=active,inactive`, but always return active careteams simply because there are no `inactive` matches.

@arscan - we are running in to this same issue.  We do support multipleOr for CareTeam.status, so if you send in a query for status=active,inactive we'll handle that, but we'll only ever have a single CareTeam, so Inferno will never be able to discover the additional status value to send in on the query for USCCT-08.

I think regardless of what 3.2.0 does, it seems like Inferno might offer an option to prompt for a list of statuses that could be search on rather requiring multiple CareTeam resources to drive the to auto-discover.  Thoughts?

**Comment by yunwwang** [comment] 2021-08-16 14:04
@cooperthompson @bh021790 I think we need ONC's instruction on this issue. Inferno has to follow the requirement in US Core 3.1.1 which is mandated by the test procedure. Inferno may take some clarification but cannot backport updates from US Core 4.0.0 directly.

**Comment by cooperthompson** [comment] 2021-08-20 18:48
@yunwwang - I'm not sure this is necessarily a 4.0.0 vs. 3.1.1. issue.  3.1.1. requires that a server support a composite OR search on status.  However, it does not require that a server expose more than one CareTeam.  If a server only ever supports a single CareTeam resource, then the issue is that Inferno cannot detect what status values to use when testing composite OR.  

Our server _does_ support composite OR - however since we only ever support a single CareTeam, Inferno has no way to actually verify it.  I think if Inferno provides the user with a way to list the status values that Inferno should use for supporting composite OR rather than trying to auto-detect them, that could work.  Though that does push the problem down the road a bit, since a server that supports composite OR but only returns one resource won't ever return two resources for you to validate - so your OR validation would need to check that the returned resource matches at least one of the params, and not look for resources that match all of them.

**Comment by yunwwang** [comment] 2021-08-23 14:35
@cooperthompson Detecting second status value is just the first step. After sending a composite OR search, Inferno expects the response bundle contains both status values. 

> since a server that supports composite OR but only returns one resource won't ever return two resources for you to validate - so your OR validation would need to check that the returned resource matches at least one of the params, and not look for resources that match all of them.

Though a regular client may interpret server response like that, a testing application cannot follow that logic. The key point here is that server need to show a proof that it supports composite OR. Returning result without resources matching the 2nd search value does not help server to prove that.

If none of resources in the response bundle has `status=inactive`, a tester cannot distinguish that server does have match results from server magically drops the 2nd search value.

**Comment by cooperthompson** [comment] 2021-09-14 13:42
Just FYI, but we submitted a request for clarification to ONC on this.  We'll see what they say.

**Comment by yunwwang** [comment] 2021-11-10 19:14
@bh021790 @cooperthompson Inferno v1.8.0 is released. Could you verify that this issue has been addressed in this release?

**Closed** 2021-12-06 19:10 UTC
Labels: removes constraint, v1.8.0
