### ISSUE TITLE
Starting Inferno on https

### ISSUE THREAD

**Issue by Puttajunjaiah01** [onc-healthit/inferno-program#306] opened 2021-06-21 09:54 UTC
I have installed the Inferno tool locally. The default installation runs Inferno server on http://localhost:4567/.
Is it possible to run the Inferno tool locally on https instead of http?

**Comment by cooperthompson** [comment] 2021-07-12 15:36
I just wrote https://github.com/onc-healthit/inferno-program/issues/317, and I think your issue is very similar.  Running https out of the container directly is tricky I think.  Or at least if you want to not have cert warnings all over the place.

My solution was to use an Apache proxy to front the https traffic, but I still had issues (as described in issue 317) with the Inferno generated URLs.

**Comment by arscan** [comment] 2021-07-12 15:58
This is a duplicate of #314 -- I apologize for not cross-referencing these tickets and closing this one earlier. I did describe a couple of high level solutions to the problem there, including @cooperthompson's method.  Unfortunately, it sounds like that approach may require some changes to Inferno to work properly -- we'll try to work through those in the #317.

**Closed by arscan** 2021-07-12 15:58 UTC
