### ISSUE TITLE
Revoked Refreshed Token input field on the Token Revocation screen is not populated (see attachment)

### ISSUE THREAD

**Issue by IgLysk00** [onc-healthit/inferno-program#324] opened 2021-07-22 16:02 UTC
Thank you for reporting a possible bug in Inferno! Please fill in as much of the template below as you can.

**Subject of the issue**
See Issue description

**Your environment**
* Edition of inferno (Community or Program): Program
* Version of inferno: 1.6.1
* Which browser and version(s) is the bug present on?: Chrome

**Steps to reproduce**
Inferno installed on AWS. Create your AWS Inferno instance. Use Program Edition. Follow the Drummond workflow – 
Standalone Patient App, 
Standalone Patient App – Limited Access, 
Other - Public Client Standalone Launch with OpenID Connect, Token Revocation. Start running Token Revocation test.

Include:

* The selected test suite
* The URL of the FHIR server being tested
* The Test ID, if it's a problem with a specific test.
* Any required configuration options (client ID, client secret, etc.)
* Anything else needed to make the issue occur.

**Expected behavior**
The Revoked Refreshed Token field should be populated

**Actual behavior**
![image](https://user-images.githubusercontent.com/73243391/126670742-a7bcf300-af04-4c4d-9fc4-c6cf97d37b6d.png)

**Comment by arscan** [comment] 2021-07-22 16:37
Thanks for the report!  This does appear to be an issue with how we ordered some of the tests, if the expectation is that all these fields will be prefilled so the tester doesn't need to type them in (which is a valid expectation!).  The last launch that occurred needs to have been granted the `offline_access` or `online_access` scope, because we are prefilling these fields based on data from the last launch.  The 'Public Client Standalone Launch with OpenID Connect' does not use those scopes, therefore shouldn't return a refresh token, and therefore that field won't be prepopulated if run right after that launch.

Could you try this sequence, but instead run `Token Revocation` prior to the `Public Client Standalone Launch with OpenID Connect`?  That way, it will prefill the field with the refresh token that should have been granted during the limited access launch, which now includes the 'offline_access' scope?  If that works, we should reorder these in the interface, or at least add some clarifying language stating that 

This has also exposed what looks to be a deficiency in our reference server's mocked SMART interface too, which we are looking into.

**Comment by IgLysk00** [comment] 2021-07-23 17:12
Tried to execute Token Revocation prior to Public Client Standalone Launch with OpenID. The result is the same - the input field on the screen is not populated.

I am adding just for information excerpt from the Drummond Group Proctor Sheet.  There is no reference in this step that this field should be populated manually. Also, as I mentioned earlier, Drummond requires this step to be executed after Public Client Standalone Launch with OpenID.
![image](https://user-images.githubusercontent.com/73243391/126817171-b548f4a2-dae0-44a7-943a-d2e4c8357116.png)

**Comment by arscan** [comment] 2021-07-23 19:42
Yes, I understand that the proctor sheet dictates this order.  I think, given the way the tests work, we may need to either update the tests or the order in which the proctor sheet says they need to be run so the data is prefilled properly. Thanks for helping me verifying the cause first though.

I'm surprised that running the Token Revocation test prior to the Public Client Launch with OpenID Connect scopes didn't cause the data to be prefilled.

To be 100% sure, could you:

1) Start a new test session
2) Run *only* the `Standalone Patient App` test, and confirm that it passes
3) Go to the "Other -> Token Revocation" test, click "Run" to get the popup, and see if the "Revoked Bearer Token" and "Revoked Refresh Token" is populated or empty.

I apologize if this is just what you did, but I'd like to make sure that you are running just those exact steps so we can track down what is causing the refresh token from disappearing.

**Comment by yunwwang** [comment] 2021-08-02 13:06
@IgLysk00 This is issue is fixed in Inferno Program v1.6.2

**Comment by arscan** [comment] 2021-08-04 16:05
Hi @IgLysk00 -- we believe we resolved this in v1.6.2, when you have a chance take a look and let us know (here or in a new ticket) if the issue isn't yet resolved from your perspective.   Thanks!

**Closed by arscan** 2021-08-04 16:05 UTC
Labels: v1.6.2

**Comment by IgLysk00** [comment] 2021-08-09 18:51
It works. Thanks.

***@***.***
